# Site
repository: veronikahristozova/veronikahristozova.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Veronika Atanasova
title: iOS Developer and Team Lead 
email: veronikahristozova@gmail.com
phone: "+359898287877"

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  veronikahristozova
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: veronika-a-969949113
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Veronika and I'm an iOS Developer and Team Lead.
  Beyond shipping apps, I’m passionate about software engineering as a whole - from brainstorming ideas to planning and delivering software that is actually used by someone.
  I love following Apple events, and <mark>WWDC</mark> is one of my favourites - every session feels like a peek at where the platform is headed next.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: "InaMatch: Pair Matching Game"
        link: https://apps.apple.com/bg/app/inamatch-pair-matching-game/id6770115423
        link_text: AppStore link 🔗
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is my very first personal iOS game published on the AppStore
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>SwiftUI</mark> from Stanford University iOS course and it has since grown into a fully fledged game app. I manage its ASO and the entire AppStore publishing, analysis and optimization. I have integrated Apple's <mark>GameCenter</mark> and leaderboard.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tumba Solutions
        link: https://www.tumba.solutions/
        # link_text: boringcompany.com
        sub_title: Team Lead
        caption: August 2025 - Present
        quote: >
          Managing team of iOS and Android developers. Measuring KPIs, setting team and personal goals for everyone on the team.
        description: | # this will include new lines to allow paragraphs
            My role as team lead includes onboarding new people, communicating with clients, gathering and analyzing client feedback, translating it into Objective Key-Results, career development for teammates and direct repoting to C-level.

      - layout: left
        title: Tumba Solutions
        link: https://www.tumba.solutions/
        # link_text: boringcompany.com
        sub_title: iOS Developer
        caption: September 2019 - July 2025
        quote: >
          I was part of the main iOS team and have contributed to various iOS projects. I was leading MVP pilot test project and organizing the company's monthly Tech Talks.
        description: | # this will include new lines to allow paragraphs
            As team member of one of the largest US news publishing iOS app I have contributed to the <mark>CI/CD</mark> setup, participated in migrating the project from UIKit to SwiftUI, consuming <mark>GraphQL</mark> and RESTful APIs. <mark>SPM</mark> modularization of the project.
            Other areas I am familiar with are: Rich Push Notifications, watchOS, Google ads, App Clips.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sofia University
        caption: 2013 - 2017
        sub_title: BSc Computer Science
        quote: >
          All coursework completed, State examination pending
        description: | # this will include new lines to allow paragraphs
          I have compelted elective course "Mobile development" which sparked my interest in iOS development.

      - layout: left
        title: Mathematics High School
        caption: 2008 - 2013
        sub_title: Mathematics and Informatics
        quote: >
          Graduated with highest honors
        description: | # this will include new lines to allow paragraphs
          Competed in mathematics and informatics competitions.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in games and mobile apps some of my other interests and hobbies are:
      - Snowboarding 🏂
      - Gym 🏋🏼‍♂️
      - Gardening 🪴

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-remote-theme
 - jekyll-seo-tag
